{"ast":null,"code":"\"use strict\";\n\nvar __extends = this && this.__extends || function () {\n  var extendStatics = function (d, b) {\n    extendStatics = Object.setPrototypeOf || {\n      __proto__: []\n    } instanceof Array && function (d, b) {\n      d.__proto__ = b;\n    } || function (d, b) {\n      for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];\n    };\n    return extendStatics(d, b);\n  };\n  return function (d, b) {\n    extendStatics(d, b);\n    function __() {\n      this.constructor = d;\n    }\n    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());\n  };\n}();\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\nvar ts_custom_error_1 = require(\"ts-custom-error\");\n/**\n * Custom Error class of type Exception.\n */\nvar Exception = /** @class */function (_super) {\n  __extends(Exception, _super);\n  /**\n   * Allows Exception to be constructed directly\n   * with some message and prototype definition.\n   */\n  function Exception(message) {\n    if (message === void 0) {\n      message = undefined;\n    }\n    var _this = _super.call(this, message) || this;\n    _this.message = message;\n    return _this;\n  }\n  return Exception;\n}(ts_custom_error_1.CustomError);\nexports.default = Exception;","map":{"version":3,"sources":["../../src/core/Exception.ts"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;AAAA,IAAA,iBAAA,GAAA,OAAA,CAAA,iBAAA,CAAA;AAEA;;AAEG;AACH,IAAA,SAAA,GAAA,aAAA,UAAA,MAAA,EAAA;EAAuC,SAAA,CAAA,SAAA,EAAA,MAAA,CAAA;EAErC;;;AAGG;EACH,SAAA,SAAA,CACS,OAA2B,EAAA;IAA3B,IAAA,OAAA,KAAA,KAAA,CAAA,EAAA;MAAA,OAAA,GAAA,SAA2B;IAAA;IADpC,IAAA,KAAA,GAGE,MAAA,CAAA,IAAA,CAAA,IAAA,EAAM,OAAO,CAAC,IAAA,IAAA;IAFP,KAAA,CAAA,OAAO,GAAP,OAAO;;EAGhB;EACF,OAAA,SAAC;AAAD,CAAC,CAXsC,iBAAA,CAAA,WAAW,CAAA","sourceRoot":"","sourcesContent":["\"use strict\";\nvar __extends = (this && this.__extends) || (function () {\n    var extendStatics = function (d, b) {\n        extendStatics = Object.setPrototypeOf ||\n            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||\n            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };\n        return extendStatics(d, b);\n    };\n    return function (d, b) {\n        extendStatics(d, b);\n        function __() { this.constructor = d; }\n        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());\n    };\n})();\nObject.defineProperty(exports, \"__esModule\", { value: true });\nvar ts_custom_error_1 = require(\"ts-custom-error\");\n/**\n * Custom Error class of type Exception.\n */\nvar Exception = /** @class */ (function (_super) {\n    __extends(Exception, _super);\n    /**\n     * Allows Exception to be constructed directly\n     * with some message and prototype definition.\n     */\n    function Exception(message) {\n        if (message === void 0) { message = undefined; }\n        var _this = _super.call(this, message) || this;\n        _this.message = message;\n        return _this;\n    }\n    return Exception;\n}(ts_custom_error_1.CustomError));\nexports.default = Exception;\n//# sourceMappingURL=Exception.js.map"]},"metadata":{},"sourceType":"script"}